### ISSUE TITLE
Conformance Test at ONVIF Device Test tool

### ISSUE THREAD

**Issue by wavesys1** [onvif/testspecs#19]
Hi,

We are trying to upload our product i.e. CCTV camera at ONVIF portal. When we are doing the procedure over Device Test Tool we are getting the failed cases (30-40) every time. Please help us to complete the procedure so we can upload our product at ONVIF portal. 

Note : Please guide us to generate the interface guide too.

Thanks

**Comment by wavesys1** [comment]
Hi,

Could any one help me into this.

Thanks

**Comment by madhurao68** [comment]
Hi
We will need details on the failed tests to investigate. 

Help on the interface guide is available under Test Tool Download link at
https://www.onvif.org/member-portal/test-tool-download

Hope this helps!

**Comment by baldvin137** [comment]
General comment for this type of questions:
- The Device Test Tool (DTT) has an extensive Help section that describes how to use the test tool. 
- The tests done by the DTT are extensively described in the test specifications. 
- The test results in the DTT include detailed information on what failed and why.
- Please use the above resources to troubleshoot any problems you have with the DTT.
- If you still believe that there is an issue with the DTT, please provide detailed information on the problem and why you believe that the problem is in the DTT and not in the Device Under Test.
